force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>The logs of the error occuring</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Log_DateTime__c</fullName>
    <description>The date and time of error</description>
    <inlineHelpText>The date and time of error</inlineHelpText>
    <label>Log DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Stores the Complete Stack Track about the Problem</description>
    <inlineHelpText>Stores the Complete Stack Track about the Problem</inlineHelpText>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <inlineHelpText>The Name of Either Apex Class or Apex Trigger</inlineHelpText>
    <label>Process Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogInsertion.cls
public with sharing class ErrorLogInsertion {
    public static void LogInsertion(DateTime logDateTime, string logDetails, string processName) {

        Error_Log__c errorLog = new Error_Log__c(
            Log_DateTime__c=logDateTime,
            Log_Details__c=logDetails,
            Process_Name__c=processName
        );
        try{
            insert errorLog;
        }
        catch(Exception e){
            system.debug('Error occured while inserting Error Log'+e.getMessage());
        }

    }
}